name: CI

on:
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/ci.yml'
  push:
    branches: [master]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/ci.yml'

jobs:
  Test:
    strategy:
      fail-fast: false

      matrix:
        platform:
        - { target: x86_64-pc-windows-gnu, os: windows-latest }
        - { target: x86_64-pc-windows-msvc, os: windows-latest }
        - { target: aarch64-pc-windows-msvc, os: windows-11-arm }
        - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
        - { target: x86_64-unknown-linux-musl, os: ubuntu-latest }
        - { target: aarch64-unknown-linux-gnu, os: ubuntu-24.04-arm }
        - { target: aarch64-unknown-linux-musl, os: ubuntu-24.04-arm }
        - { target: x86_64-apple-darwin, os: macos-15-intel }
        - { target: aarch64-apple-darwin, os: macos-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Target add and log toolchain info
      run: |
        rustup target add ${{ matrix.platform.target }}
        rustup --version
        rustup toolchain list
        rustup target list --installed

    - name: Build
      run: cargo build --verbose --target ${{ matrix.platform.target }}

    - name: Test
      run: cargo test --verbose --target ${{ matrix.platform.target }}

    env:
      RUST_BACKTRACE: 1
      RUST_INCREMENTAL: 0
      RUSTFLAGS: "-C debuginfo=0"
